export const sponsors = {
    // Platinum Tier
    protolabs: {
        image: "/images/sponsors/Protolabs_logo_white.png",
        img_alt: "Protolabs sponsor logo",
        link: "https://protolabs.com",
        tier: "platinum",
        display_height: 96,
    },
    marotta: {
        image: "/images/sponsors/marotta_controls_logo.png",
        img_alt: "Marotta Controls",
        link: "https://www.marotta.com/",
        tier: "platinum",
        display_height: 48,
        banner_height: 40,
    },
    national_instruments: {
        image: "/images/sponsors/national-instruments.png",
        img_alt: "National Instruments sponsor logo",
        link: "https://ni.com",
        tier: "platinum",
        display_height: 112,
    },
    notion: {
        image: "/images/sponsors/notion-logo-white.png",
        img_alt: "Notion sponsor logo",
        link: "https://www.notion.com",
        tier: "platinum",
        display_height: 96,
    },
    // Gold Tier
    honeywell: {
        image: "/images/sponsors/Honeywell_logo.png",
        img_alt: "Honeywell sponsor logo",
        link: "https://www.honeywell.com/us/en",
        tier: "gold",
        display_height: 32,
        banner_height: 70,
    },
    pepc: {
        name: "Purdue Engineering Presidents' Council",
        image: "/images/sponsors/pepc_logo.png",
        img_alt: "Purdue Engineering Presidents' Council text",
        link: "https://engineering.purdue.edu/Engr/Academics/Undergraduate/PEPC",
        tier: "gold",
        display_height: 90,
    },
    l3harris: {
        image: "/images/sponsors/l3harris_logo.png",
        img_alt: "L3HARRIS",
        link: "https://www.l3harris.com/",
        tier: "gold",
        display_height: 64,
    },
    msm: {
        image: "/images/sponsors/msmlogo-1764661165.jpg",
        img_alt: "MSM sponsor logo",
        link: "https://https://www.metalsupermarkets.com",
        tier: "gold",
        display_height: 64,
    },
    blue_origin: {
        image: "/images/sponsors/blue_origin_logo.png",
        img_alt: "Blue Origin",
        link: "https://www.blueorigin.com/",
        tier: "gold",
        display_height: 96,
        banner_height: 100,
    },
    kulite: {
        image: "/images/sponsors/kulite_logo.png",
        img_alt: "Kulite",
        link: "https://kulite.com/",
        tier: "gold",
        display_height: 48,
        banner_height: 75,
    },
    lockheed_martin: {
        image: "/images/sponsors/lockheed_martin_logo.png",
        img_alt: "Lockheed Martin",
        link: "https://www.lockheedmartin.com/",
        tier: "gold",
        display_height: 80,
        banner_height: 140,
    },
    technetics: {
        image: "/images/sponsors/technetics-logo.png",
        img_alt: "Technetics sponsor logo",
        link: "https://technetics.com/",
        tier: "gold",
        display_height: 64,
    },
    imaginarium: {
        image: "/images/sponsors/imaginarium_logo.png",
        img_alt: "Imaginarium",
        link: "https://imaginarium.io",
        tier: "gold",
        display_height: 80,
    },
    // Silver Tier
    polymaker: {
        image: "/images/sponsors/Polymaker_Logo_TEAL.png",
        img_alt: "Polymaker sponsor logo",
        link: "https://polymaker.com/",
        tier: "silver",
        display_height: 64,
    },
    ansys: {
        image: "/images/sponsors/ansys_logo.png",
        img_alt: "Ansys sponsor logo",
        link: "https://ansys.com",
        tier: "silver",
        display_height: 64,
    },
    pesc: {
        image: "/images/sponsors/PESC_logo-gold.png",
        img_alt: "PESC sponsor logo",
        link: "https://www.purdueesc.org/",
        tier: "silver",
        display_height: 64,
    },
    bidc: {
        image: "/images/sponsors/bechtel-logo.png",
        image_dark: "/images/sponsors/BIDC_V-Full-RGB.png",
        img_alt: "Bechtel Innovation Design Center sponsor logo",
        link: "https://www.purdue.edu/bidc/",
        tier: "platinum",
        display_height: 48,
        banner_height: 70,
    },
    cfturbo: {
        image: "/images/sponsors/CFturbo-Logo-white-transparent.png",
        img_alt: "CFturbo sponsor logo",
        link: "https://cfturbo.com/",
        tier: "silver",
        display_height: 32,
        banner_height: 70,
    },
    three_d_connexion: {
        image: "/images/sponsors/3dconnexion_logo_white.png",
        img_alt: "3D Connexion sponsor logo",
        link: "https://3dconnexion.com/us/",
        tier: "silver",
        display_height: 32,
        banner_height: 80,
    },
    purdue_mechanical_eng: {
        image: "/images/sponsors/MechEng_H-Full-Reverse-RGB.png",
        img_alt: "Purdue University Mechanical Engineering sponsor logo",
        link: "https://engineering.purdue.edu/ME",
        tier: "silver",
        display_height: 32,
        banner_height: 70,
    },
    snyder: {
        name: "Snyder & Lehnen Sheet Metal",
        link: "https://www.snyderandlehnen.com/",
        tier: "silver",
    },
    aea: {
        image: "/images/sponsors/aea-logo.png",
        img_alt: "AEA sponsor logo",
        link: "https://americanearthanchors.com/",
        tier: "silver",
        display_height: 48,
    },
    proportion_air: {
        image: "/images/sponsors/proportion_air_logo.png",
        img_alt: "Proportion Air sponsor logo",
        link: "https://www.proportionair.com/",
        tier: "silver",
        display_height: 32,
        banner_height: 50,
    },
    seco_seals: {
        image: "/images/sponsors/seco-seals-placeholder_1-4132690478.png",
        img_alt: "SECO Seals sponsor logo",
        link: "https://secoseals.com/",
        tier: "silver",
        display_height: 48,
        banner_height: 110,
    },
    interstate_am: {
        image: "/images/sponsors/interstateam_white.png",
        img_alt: "Interstate Advanced Materials sponsor logo",
        link: "https://interstateam.com/",
        tier: "silver",
        display_height: 48,
        banner_height: 80,
    },
    precision_piping: {
        image: "/images/sponsors/precision-piping-products_light.png",
        img_alt: "Precision Piping Products sponsor logo",
        link: "https://www.precisionpipingproducts.com/",
        tier: "silver",
        display_height: 48,
    },
    altair: {
        image: "/images/sponsors/siemens_logo.png",
        img_alt: "Altair owned by Siemens",
        link: "https://altair.com/",
        tier: "silver",
        display_height: 32,
        banner_height: 70,
    },
    drake_plastics: {
        image: "/images/sponsors/drake_plastics_logo.png",
        img_alt: "drake plastics",
        link: "https://drakeplastics.com/",
        tier: "silver",
        display_height: 100,
        banner_height: 90,
    },
    synnax: {
        image: "/images/sponsors/synnax_logo.png",
        img_alt: "Synnax Labs",
        link: "https://synnaxlabs.com/",
        tier: "silver",
        display_height: 48,
    },
    sendcutsend: {
        image: "/images/sponsors/sendcutsend_logo.png",
        img_alt: "Send cut send",
        link: "https://sendcutsend.com/",
        tier: "silver",
        display_height: 32,
        banner_height: 60,
    },
    northside_mt: {
        image: "/images/sponsors/northside_mt.png",
        img_alt: "Northside Machine & Tool",
        link: "https://www.northsidemt.com/",
        tier: "silver",
        display_height: 80,
    },
};

export const priorSponsors = {
    shreve: {
        image: "/images/sponsors/shreve_hall_club_mascot.jpg",
        img_alt: "Shreve Hall Club sponsor mascot",
        link: "https://web.ics.purdue.edu/~shreve/"
    },
     revolution: {
        image: "/images/sponsors/Revolution-Barbeque-Icon-transparent.png",
        img_alt: "Revolution Barbeque sponsor logo",
        link: "https://www.revolution-bbq.com/"
    },
    chipotle: {
        image: "/images/sponsors/chipotle.png",
        img_alt: "Chipotle sponsor logo",
        link: "https://chipotle.com"
    },
    dyrobes: {
        image: "/images/sponsors/dyrobes.png",
        img_alt: "Dyrobes sponsor logo",
        link: "https://dyrobes.com/"
    },
}
